services:
  pharma_db:
    image: postgres:15-alpine
    env_file:
      - ./pharma-backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pharma_backend:
    build: ./pharma-backend
    volumes:
      - ./pharma-backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./pharma-backend/.env
    environment:
      - DB_HOST=pharma_db
    depends_on:
      - pharma_db
    restart: unless-stopped

  pharma_frontend:
    build: ./pharma-front-end
    ports:
      - "3000:80"
    depends_on:
      - pharma_backend
    restart: unless-stopped

volumes:
  pgdata: