# Generated by Django 5.2.12 on 2026-03-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom Commercial"),
                ),
                (
                    "dci",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="DCI (Optionnel)",
                    ),
                ),
                ("forme", models.CharField(max_length=100, verbose_name="Forme")),
                ("dosage", models.CharField(max_length=100, verbose_name="Dosage")),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix d'Achat"
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix de Vente"
                    ),
                ),
                (
                    "stock_actuel",
                    models.IntegerField(default=0, verbose_name="Stock Actuel"),
                ),
                (
                    "stock_minimum",
                    models.IntegerField(default=10, verbose_name="Stock Minimum"),
                ),
                (
                    "date_expiration",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'Expiration"
                    ),
                ),
                (
                    "ordonnance_requise",
                    models.BooleanField(
                        default=False, verbose_name="Ordonnance Requise"
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(
                        default=True, verbose_name="Est Actif (Soft Delete)"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicaments",
                        to="categories.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Médicament",
                "verbose_name_plural": "Médicaments",
                "ordering": ["nom"],
            },
        ),
    ]
