# Generated by Django 5.2.12 on 2026-03-10 01:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "date_vente",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de vente"
                    ),
                ),
                (
                    "total_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total TTC",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("COMPLETÉE", "Complétée"),
                            ("ANNULÉE", "Annulée"),
                        ],
                        default="COMPLETÉE",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-date_vente"],
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix Unitaire (Snapshot)",
                    ),
                ),
                (
                    "sous_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sous-total"
                    ),
                ),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medicaments.medicament",
                        verbose_name="Médicament",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="ventes.vente",
                        verbose_name="Vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Vente",
                "verbose_name_plural": "Lignes de Vente",
            },
        ),
    ]
